# Segmenting remote sensing imagery with point prompts

[![image](https://studiolab.sagemaker.aws/studiolab.svg)](https://studiolab.sagemaker.aws/import/github/opengeos/segment-geospatial/blob/main/docs/examples/sam2_point_prompts.ipynb)
[![image](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/opengeos/segment-geospatial/blob/main/docs/examples/sam2_point_prompts.ipynb)

This notebook shows how to generate object masks from point prompts with the Segment Anything Model 2 (SAM 2).

Make sure you use GPU runtime for this notebook. For Google Colab, go to `Runtime` -> `Change runtime type` and select `GPU` as the hardware accelerator.

## Install dependencies

Uncomment and run the following cell to install the required dependencies.

In [1]:
%pip install segment-geospatial[samgeo2]

Requirement already satisfied: segment-geospatial[samgeo2] in /usr/local/lib/python3.12/dist-packages (1.2.3)
Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (5.2.1)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (1.1.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (1.6.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (2.0.2)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (4.13.0.92)
Requirement already satisfied: patool in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (4.0.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (11.3.0)
Requirement already satisfied: pyproj in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (3.7.2)
Requirement already satisfied: rasterio in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (1.5.0)
Requirement already satisfied: segment_anything in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (1.0)
Requirement already satisfied: shapely in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (2.1.2)
Requirement already satisfied: smoothify in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (0.2.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (0.25.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (4.67.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (2025.11.0)
Requirement already satisfied: sam2 in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (1.1.0)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (2026.2.0)
Requirement already satisfied: rioxarray in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (0.22.0)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (0.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from segment-geospatial[samgeo2]) (1.16.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown->segment-geospatial[samgeo2]) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown->segment-geospatial[samgeo2]) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown->segment-geospatial[samgeo2]) (2.32.4)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->segment-geospatial[samgeo2]) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas->segment-geospatial[samgeo2]) (26.0)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->segment-geospatial[samgeo2]) (2.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyproj->segment-geospatial[samgeo2]) (2026.2.25)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial[samgeo2]) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial[samgeo2]) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial[samgeo2]) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial[samgeo2]) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial[samgeo2]) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial[samgeo2]) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial[samgeo2]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial[samgeo2]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial[samgeo2]) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial[samgeo2]) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial[samgeo2]) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial[samgeo2]) (2.9.0.post0)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial[samgeo2]) (2.4.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial[samgeo2]) (25.4.0)
Requirement already satisfied: click!=8.2.*,>=4.0 in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial[samgeo2]) (8.3.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial[samgeo2]) (0.7.2)
Requirement already satisfied: hydra-core>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from sam2->segment-geospatial[samgeo2]) (1.3.2)
Requirement already satisfied: iopath>=0.1.10 in /usr/local/lib/python3.12/dist-packages (from sam2->segment-geospatial[samgeo2]) (0.1.10)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial[samgeo2]) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->segment-geospatial[samgeo2]) (1.4.2)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image->segment-geospatial[samgeo2]) (2.37.3)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image->segment-geospatial[samgeo2]) (2026.3.3)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image->segment-geospatial[samgeo2]) (0.5)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from smoothify->segment-geospatial[samgeo2]) (1.5.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->segment-geospatial[samgeo2]) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->segment-geospatial[samgeo2]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->segment-geospatial[samgeo2]) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->segment-geospatial[samgeo2]) (0.16.0)
Requirement already satisfied: omegaconf<2.4,>=2.2 in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.3.2->sam2->segment-geospatial[samgeo2]) (2.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.3.2->sam2->segment-geospatial[samgeo2]) (4.9.3)
Requirement already satisfied: portalocker in /usr/local/lib/python3.12/dist-packages (from iopath>=0.1.10->sam2->segment-geospatial[samgeo2]) (3.2.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas->segment-geospatial[samgeo2]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas->segment-geospatial[samgeo2]) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->segment-geospatial[samgeo2]) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->segment-geospatial[samgeo2]) (1.3.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown->segment-geospatial[samgeo2]) (2.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->segment-geospatial[samgeo2]) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->segment-geospatial[samgeo2]) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->segment-geospatial[samgeo2]) (2.5.0)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->segment-geospatial[samgeo2]) (1.7.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->segment-geospatial[samgeo2]) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->segment-geospatial[samgeo2]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->segment-geospatial[samgeo2]) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->segment-geospatial[samgeo2]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->segment-geospatial[samgeo2]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub->segment-geospatial[samgeo2]) (0.1.2)

In [2]:
%pip install localtileserver

Requirement already satisfied: localtileserver in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from localtileserver) (8.3.1)
Requirement already satisfied: flask<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from localtileserver) (3.1.3)
Requirement already satisfied: Flask-Caching in /usr/local/lib/python3.12/dist-packages (from localtileserver) (2.3.1)
Requirement already satisfied: flask-cors in /usr/local/lib/python3.12/dist-packages (from localtileserver) (6.0.2)
Requirement already satisfied: flask-restx>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from localtileserver) (1.3.2)
Requirement already satisfied: rio-tiler in /usr/local/lib/python3.12/dist-packages (from localtileserver) (9.0.0)
Requirement already satisfied: rio-cogeo in /usr/local/lib/python3.12/dist-packages (from localtileserver) (7.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from localtileserver) (2.32.4)
Requirement already satisfied: server-thread in /usr/local/lib/python3.12/dist-packages (from localtileserver) (0.3.0)
Requirement already satisfied: scooby in /usr/local/lib/python3.12/dist-packages (from localtileserver) (0.11.0)
Requirement already satisfied: werkzeug in /usr/local/lib/python3.12/dist-packages (from localtileserver) (3.1.6)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from flask<4,>=2.0.0->localtileserver) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from flask<4,>=2.0.0->localtileserver) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from flask<4,>=2.0.0->localtileserver) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from flask<4,>=2.0.0->localtileserver) (3.0.3)
Requirement already satisfied: aniso8601>=0.82 in /usr/local/lib/python3.12/dist-packages (from flask-restx>=1.3.0->localtileserver) (10.0.1)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from flask-restx>=1.3.0->localtileserver) (4.26.0)
Requirement already satisfied: referencing in /usr/local/lib/python3.12/dist-packages (from flask-restx>=1.3.0->localtileserver) (0.37.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from flask-restx>=1.3.0->localtileserver) (6.5.2)
Requirement already satisfied: cachelib>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask-Caching->localtileserver) (0.13.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->localtileserver) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->localtileserver) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->localtileserver) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->localtileserver) (2026.2.25)
Requirement already satisfied: morecantile<8.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from rio-cogeo->localtileserver) (7.0.3)
Requirement already satisfied: pydantic~=2.0 in /usr/local/lib/python3.12/dist-packages (from rio-cogeo->localtileserver) (2.12.3)
Requirement already satisfied: rasterio>=1.3.3 in /usr/local/lib/python3.12/dist-packages (from rio-cogeo->localtileserver) (1.5.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rio-tiler->localtileserver) (25.4.0)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from rio-tiler->localtileserver) (6.2.6)
Requirement already satisfied: color-operations in /usr/local/lib/python3.12/dist-packages (from rio-tiler->localtileserver) (0.2.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from rio-tiler->localtileserver) (0.28.1)
Requirement already satisfied: numexpr in /usr/local/lib/python3.12/dist-packages (from rio-tiler->localtileserver) (2.14.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rio-tiler->localtileserver) (2.0.2)
Requirement already satisfied: pystac<2.0,>=1.9 in /usr/local/lib/python3.12/dist-packages (from rio-tiler->localtileserver) (1.14.3)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (from server-thread->localtileserver) (0.41.0)
Requirement already satisfied: pyproj<4.0,>=3.1 in /usr/local/lib/python3.12/dist-packages (from morecantile<8.0,>=5.0->rio-cogeo->localtileserver) (3.7.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.0->rio-cogeo->localtileserver) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.0->rio-cogeo->localtileserver) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.0->rio-cogeo->localtileserver) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.0->rio-cogeo->localtileserver) (0.4.2)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from pystac<2.0,>=1.9->rio-tiler->localtileserver) (2.9.0.post0)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.3.3->rio-cogeo->localtileserver) (2.4.0)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.3.3->rio-cogeo->localtileserver) (0.7.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.3.3->rio-cogeo->localtileserver) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->rio-tiler->localtileserver) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->rio-tiler->localtileserver) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->rio-tiler->localtileserver) (0.16.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->flask-restx>=1.3.0->localtileserver) (2025.9.1)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->flask-restx>=1.3.0->localtileserver) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->pystac<2.0,>=1.9->rio-tiler->localtileserver) (1.17.0)

In [3]:
%pip install leafmap

Requirement already satisfied: leafmap in /usr/local/lib/python3.12/dist-packages (0.60.4)
Requirement already satisfied: anywidget in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.9.21)
Requirement already satisfied: bqplot in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.12.45)
Requirement already satisfied: duckdb>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from leafmap) (1.5.0)
Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.20.0)
Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (from leafmap) (5.2.1)
Requirement already satisfied: geojson in /usr/local/lib/python3.12/dist-packages (from leafmap) (3.2.0)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from leafmap) (1.1.3)
Requirement already satisfied: ipyevents in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.0.4)
Requirement already satisfied: ipyfilechooser in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.6.0)
Requirement already satisfied: ipyleaflet in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.20.0)
Requirement already satisfied: ipyvuetify in /usr/local/lib/python3.12/dist-packages (from leafmap) (1.11.3)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from leafmap) (7.7.1)
Requirement already satisfied: maplibre in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.3.6)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from leafmap) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from leafmap) (5.24.1)
Requirement already satisfied: pystac-client in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.9.0)
Requirement already satisfied: python-box in /usr/local/lib/python3.12/dist-packages (from leafmap) (7.4.1)
Requirement already satisfied: scooby in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.11.0)
Requirement already satisfied: whiteboxgui in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.3.0)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from leafmap) (2025.11.0)
Requirement already satisfied: psygnal>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from anywidget->leafmap) (0.15.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from anywidget->leafmap) (4.15.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (5.7.1)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (3.0.16)
Requirement already satisfied: traittypes>=0.0.6 in /usr/local/lib/python3.12/dist-packages (from bqplot->leafmap) (0.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2025.3)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (3.25.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (4.67.3)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (2.1.2)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet->leafmap) (0.20.0)
Requirement already satisfied: ipyvue<2,>=1.7 in /usr/local/lib/python3.12/dist-packages (from ipyvuetify->leafmap) (1.12.0)
Requirement already satisfied: eval-type-backport in /usr/local/lib/python3.12/dist-packages (from maplibre->leafmap) (0.3.1)
Requirement already satisfied: pydantic>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from maplibre->leafmap) (2.12.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->leafmap) (9.1.4)
Requirement already satisfied: pystac>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from pystac[validation]>=1.10.0->pystac-client->leafmap) (1.14.3)
Requirement already satisfied: ipytree in /usr/local/lib/python3.12/dist-packages (from whiteboxgui->leafmap) (0.2.2)
Requirement already satisfied: whitebox in /usr/local/lib/python3.12/dist-packages (from whiteboxgui->leafmap) (2.3.6)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (6.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium->leafmap) (3.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.4.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas->leafmap) (2026.2.25)
Requirement already satisfied: jsonschema~=4.18 in /usr/local/lib/python3.12/dist-packages (from pystac[validation]>=1.10.0->pystac-client->leafmap) (4.26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->leafmap) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (2.5.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.5.7)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown->leafmap) (2.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->leafmap) (1.7.1)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.12/dist-packages (from whitebox->whiteboxgui->leafmap) (8.3.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets->leafmap) (0.8.6)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.30.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (5.9.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (7.17.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.3.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets->leafmap) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets->leafmap) (0.6.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (4.9.4)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.2.4)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.21.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.4.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (3.0)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (4.12.1)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (7.7.0)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.9.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (3.0.0)

In [4]:
%pip install -U segment-geospatial

Requirement already satisfied: segment-geospatial in /usr/local/lib/python3.12/dist-packages (1.2.3)
Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (5.2.1)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (1.1.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (1.6.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (2.0.2)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (4.13.0.92)
Requirement already satisfied: patool in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (4.0.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (11.3.0)
Requirement already satisfied: pyproj in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (3.7.2)
Requirement already satisfied: rasterio in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (1.5.0)
Requirement already satisfied: segment_anything in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (1.0)
Requirement already satisfied: shapely in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (2.1.2)
Requirement already satisfied: smoothify in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (0.2.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (0.25.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (4.67.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from segment-geospatial) (2025.11.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown->segment-geospatial) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown->segment-geospatial) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown->segment-geospatial) (2.32.4)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->segment-geospatial) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas->segment-geospatial) (26.0)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->segment-geospatial) (2.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyproj->segment-geospatial) (2026.2.25)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->segment-geospatial) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->segment-geospatial) (2.9.0.post0)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial) (2.4.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial) (25.4.0)
Requirement already satisfied: click!=8.2.*,>=4.0 in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial) (8.3.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from rasterio->segment-geospatial) (0.7.2)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from smoothify->segment-geospatial) (1.5.3)
Requirement already satisfied: scipy>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from smoothify->segment-geospatial) (1.16.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->segment-geospatial) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->segment-geospatial) (1.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->segment-geospatial) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->segment-geospatial) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->segment-geospatial) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->segment-geospatial) (0.16.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas->segment-geospatial) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas->segment-geospatial) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->segment-geospatial) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->segment-geospatial) (1.3.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown->segment-geospatial) (2.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->segment-geospatial) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->segment-geospatial) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->segment-geospatial) (2.5.0)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->segment-geospatial) (1.7.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->segment-geospatial) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->segment-geospatial) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->segment-geospatial) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->segment-geospatial) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->segment-geospatial) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub->segment-geospatial) (0.1.2)

## Import libraries

In [5]:
import leafmap
from samgeo import SamGeo2
from samgeo.common import regularize

## Create an interactive map

In [6]:
m = leafmap.Map(center=[47.653287, -117.588070], zoom=16, height="800px")
m.add_basemap("Satellite")
m

Map(center=[47.653287, -117.58807], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title'…

## Download a sample image

Pan and zoom the map to select the area of interest. Use the draw tools to draw a polygon or rectangle on the map. If no geometry is drawn, the default bounding box will be used.

In [7]:
if m.user_roi is not None:
    bbox = m.user_roi_bounds()
else:
    bbox = [-117.6029, 47.65, -117.5936, 47.6563]

In [8]:
image = "satellite.tif"
leafmap.map_tiles_to_geotiff(
    output=image, bbox=bbox, zoom=18, source="Satellite", overwrite=True
)

Downloaded image 1/56
Downloaded image 2/56
Downloaded image 3/56
Downloaded image 4/56
Downloaded image 5/56
Downloaded image 6/56
Downloaded image 7/56
Downloaded image 8/56
Downloaded image 9/56
Downloaded image 10/56
Downloaded image 11/56
Downloaded image 12/56
Downloaded image 13/56
Downloaded image 14/56
Downloaded image 15/56
Downloaded image 16/56
Downloaded image 17/56
Downloaded image 18/56
Downloaded image 19/56
Downloaded image 20/56
Downloaded image 21/56
Downloaded image 22/56
Downloaded image 23/56
Downloaded image 24/56
Downloaded image 25/56
Downloaded image 26/56
Downloaded image 27/56
Downloaded image 28/56
Downloaded image 29/56
Downloaded image 30/56
Downloaded image 31/56
Downloaded image 32/56
Downloaded image 33/56
Downloaded image 34/56
Downloaded image 35/56
Downloaded image 36/56
Downloaded image 37/56
Downloaded image 38/56
Downloaded image 39/56
Downloaded image 40/56
Downloaded image 41/56
Downloaded image 42/56
Downloaded image 43/56
Downloaded image 44/56
Downloaded image 45/56
Downloaded image 46/56
Downloaded image 47/56
Downloaded image 48/56
Downloaded image 49/56
Downloaded image 50/56
Downloaded image 51/56
Downloaded image 52/56
Downloaded image 53/56
Downloaded image 54/56
Downloaded image 55/56
Downloaded image 56/56
Saving GeoTIFF. Please wait...
Image saved to satellite.tif

You can also use your own image. Uncomment and run the following cell to use your own image.

In [ ]:
image = '/content/mosaic_z19_2816x2816.tif'

Display the downloaded image on the map.

In [ ]:
m.layers[-1].visible = False
m.add_raster(image, layer_name="Image")
m

In [29]:
from google.colab import output
output.enable_custom_widget_manager()

Support for third party widgets will remain active for the duration of the session. To disable support:

In [28]:
from google.colab import output
output.disable_custom_widget_manager()

## Initialize SAM class

Set `automatic=False` to enable the `SAM2ImagePredictor`.

In [ ]:
sam = SamGeo2(
    model_id="sam2-hiera-large",
    automatic=False,
)

Specify the image to segment.

In [ ]:
sam.set_image(image)

## Segment the image

Use the `predict_by_points()` method to segment the image with specified point coordinates. You can use the draw tools to add place markers on the map. If no point is added, the default sample points will be used.

In [ ]:
if m.user_rois is not None:
    point_coords_batch = m.user_rois
else:
    point_coords_batch = [
        [-117.599896, 47.655345],
        [-117.59992, 47.655167],
        [-117.599928, 47.654974],
        [-117.599518, 47.655337],
    ]

Segment the objects using the point prompts and save the output masks.

In [14]:
sam.predict_by_points(
    point_coords_batch=point_coords_batch,
    point_crs="EPSG:4326",
    output="mask.tif",
    dtype="uint8",
)

## Display the result

Add the segmented image to the map.

In [15]:
m.add_raster("mask.tif", cmap="viridis", nodata=0, opacity=0.7, layer_name="Mask")
m

Map(center=[47.65315, -117.59825000000001], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_i…

![image](https://github.com/user-attachments/assets/49e413b9-e159-4d72-bf23-a0318bc82d44)

## Use an existing vector dataset as points prompts

Alternatively, you can specify a file path or HTTP URL to a vector dataset containing point geometries.

In [16]:
geojson = "https://github.com/opengeos/datasets/releases/download/places/wa_building_centroids.geojson"

Display the vector data on the map.

In [17]:
m = leafmap.Map()
m.add_raster(image, layer_name="Image")
m.add_circle_markers_from_xy(
    geojson, radius=3, color="red", fill_color="yellow", fill_opacity=0.8
)
m

Map(center=[47.65315, -117.59825000000001], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_i…

![image](https://github.com/user-attachments/assets/f0d3ff1e-15fa-4bd3-ac15-637e8d63527d)

## Segment image with a vector dataset

Segment the image using the specified file path to the vector dataset.

In [18]:
output_masks = "building_masks.tif"

In [19]:
sam.predict_by_points(
    point_coords_batch=geojson,
    point_crs="EPSG:4326",
    output=output_masks,
    dtype="uint8",
    multimask_output=False,
)

Display the segmented masks on the map.

In [20]:
m.add_raster(
    output_masks, cmap="jet", nodata=0, opacity=0.7, layer_name="Building masks"
)
m

Map(center=[47.65315, -117.59825000000001], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_i…

![image](https://github.com/user-attachments/assets/262e1a31-1648-47d2-9e71-c85ab15b1a5c)

## Clean up the result

Remove small objects from the segmented masks, fill holes, and compute geometric properties.

In [21]:
out_vector = "building_vector.geojson"
out_image = "buildings.tif"

In [22]:
array, gdf = sam.region_groups(
    output_masks, min_size=200, out_vector=out_vector, out_image=out_image
)

In [23]:
gdf.head()

,geometry,label,area,area_bbox,area_convex,area_filled,axis_major_length,axis_minor_length,eccentricity,equivalent_diameter_area,extent,orientation,perimeter,solidity,elongation
0,"POLYGON ((-13090971.338 6049795.403, -13090971...",1,1774.0,1944.0,1816.0,1774.0,58.895639,39.335134,0.744270,47.526066,0.912551,0.054659,163.112698,0.976872,1.497278
1,"POLYGON ((-13090879.99 6049795.403, -13090879....",2,1878.0,2035.0,1910.0,1878.0,59.298140,41.181848,0.719504,48.899324,0.922850,0.049432,165.941125,0.983246,1.439910
7,"POLYGON ((-13091096.12 6049794.805, -13091096....",3,1804.0,1925.0,1830.0,1804.0,60.199043,39.122954,0.760025,47.926236,0.937143,0.077096,164.284271,0.985792,1.538714
6,"POLYGON ((-13091034.027 6049794.805, -13091034...",4,1750.0,1944.0,1799.0,1750.0,57.765236,39.539690,0.729023,47.203487,0.900206,0.042879,162.769553,0.972763,1.460943
5,"POLYGON ((-13091121.195 6049792.416, -13091121...",5,1779.0,2100.0,1853.0,1779.0,54.361282,42.936259,0.613324,47.592995,0.847143,-0.253021,164.426407,0.960065,1.266093

![image](https://github.com/user-attachments/assets/af9ffa11-8ebe-4b42-8cba-3f5bcc4912f4)

## Regularize building footprints

Regularize the building footprints using the `regularize()` method.

In [24]:
output_regularized = "building_regularized.geojson"
regularize(out_vector, output_regularized)

Collecting buildingregulariser
Downloading buildingregulariser-0.2.4-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: geopandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from buildingregulariser) (1.1.3)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from buildingregulariser) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.0->buildingregulariser) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.0->buildingregulariser) (26.0)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.0->buildingregulariser) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.0->buildingregulariser) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=1.0.0->buildingregulariser) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas>=1.0.0->buildingregulariser) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas>=1.0.0->buildingregulariser) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas>=1.0.0->buildingregulariser) (2025.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas>=1.0.0->buildingregulariser) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas>=1.0.0->buildingregulariser) (1.17.0)
Downloading buildingregulariser-0.2.4-py3-none-any.whl (19 kB)
Installing collected packages: buildingregulariser
Successfully installed buildingregulariser-0.2.4

,label,area,area_bbox,area_convex,area_filled,axis_major_length,axis_minor_length,eccentricity,equivalent_diameter_area,extent,orientation,solidity,elongation,geometry
0,1,1774.0,1944.0,1816.0,1774.0,58.895639,39.335134,0.744270,47.526066,0.912551,0.054659,0.976872,1.497278,"POLYGON ((-13090971.345 6049795.405, -13090965..."
1,2,1878.0,2035.0,1910.0,1878.0,59.298140,41.181848,0.719504,48.899324,0.922850,0.049432,0.983246,1.439910,"POLYGON ((-13090879.999 6049795.345, -13090868..."
2,8,1651.0,1748.0,1669.0,1651.0,50.799949,42.287910,0.554115,45.848866,0.944508,0.021925,0.989215,1.201288,"POLYGON ((-13091005.378 6049790.024, -13090989..."
3,6,1771.0,1927.0,1798.0,1771.0,51.205469,44.793621,0.484517,47.485864,0.919045,-0.052632,0.984983,1.143142,"POLYGON ((-13090943.191 6049790.474, -13090938..."
4,10,1392.0,1512.0,1420.0,1392.0,45.093114,40.260509,0.450393,42.099281,0.920635,0.113786,0.980282,1.120033,"POLYGON ((-13090907.465 6049787.516, -13090898..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,234,2265.0,3420.0,2318.0,2265.0,57.940265,50.427534,0.492457,53.701840,0.662281,-0.494305,0.977135,1.148981,"POLYGON ((-13090737.885 6048888.085, -13090732..."
235,236,1849.0,2193.0,1907.0,1849.0,53.288976,45.035846,0.534569,48.520304,0.843137,0.002583,0.969586,1.183257,"POLYGON ((-13090782.076 6048881.364, -13090778..."
236,238,4188.0,4756.0,4475.0,4188.0,133.077466,42.257861,0.948244,73.022786,0.880572,-1.563971,0.935866,3.149177,"POLYGON ((-13090986.857 6048874.291, -13090975..."
237,237,2140.0,2726.0,2261.0,2140.0,63.281850,44.047772,0.717987,52.198972,0.785033,1.297763,0.946484,1.436664,"POLYGON ((-13090551.025 6048876.141, -13090538..."
238,239,3626.0,5928.0,4588.0,3626.0,84.613274,63.699108,0.658219,67.946792,0.611673,-1.285738,0.790323,1.328327,"POLYGON ((-13090499.073 6048874.294, -13090488..."

Display the regularized building footprints on the map.

In [25]:
m = leafmap.Map()
m.add_raster(image, layer_name="Image")
style = {
    "color": "#ffff00",
    "weight": 2,
    "fillColor": "#7c4185",
    "fillOpacity": 0,
}
m.add_raster(out_image, cmap="tab20", opacity=0.7, nodata=0, layer_name="Buildings")
m.add_vector(
    output_regularized, style=style, layer_name="Building regularized", info_mode=None
)
m

Map(center=[47.65315, -117.59825000000001], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_i…

![image](https://github.com/user-attachments/assets/b39ee029-2089-45b8-8ac0-ba0d750cec22)

## Interactive segmentation

In [26]:
sam.show_map()

Map(center=[47.65315, -117.59825000000001], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_i…